import type { Article } from './types';

// GENERATED by scripts/genProvinceGuides.ts — do not hand-edit.
// Every number comes from Statistics Canada's published wage medians or from
// the CanPay Insights 2026 tax engine. Re-run the script after either changes.

export const provinceGuides2026: Article[] = [
  {
    id: 'province-2026-ontario',
    slug: 'ontario-take-home-pay-guide-2026',
    title: "Ontario Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Ontario workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in Ontario is $34.62 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "Ontario Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "Ontario's median full-time wage is $34.62/hr. See take-home pay at every salary, wages for every industry, and how Ontario ranks (#6 of 13) for 2026.",
    keywords: ["Ontario salary","Ontario take home pay","Ontario average salary 2026","Ontario paycheck calculator","Ontario income tax 2026","wages in Ontario"],
    category: 'province',
    tags: ["Ontario","take-home pay","wages","2026"],
    province: 'Ontario',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/ontario-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in Ontario is $34.62 an hour, about $72,000 a year, which leaves roughly $55,099 after tax in 2026. On an $80,000 salary, Ontario ranks #6 of 13 provinces and territories for take-home pay, keeping $60,303.",
    faq: [
          {
                "question": "What is the average salary in Ontario?",
                "answer": "The median full-time wage in Ontario is $34.62 an hour, about $72,000 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in Ontario?",
                "answer": "About $60,303 a year, or $5,025 a month, after federal tax, Ontario provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Ontario have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Ontario ranks #6 of 13 provinces and territories for take-home pay in 2026, keeping $60,303. That is $1,996 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Ontario?",
                "answer": "Of the sectors Statistics Canada reports for Ontario, utilities has the highest median full-time wage at $56.00 an hour — roughly $116,500 a year, or $85,270 after tax."
          },
          {
                "question": "How much of my pay do I keep in Ontario?",
                "answer": "It depends on the salary. In Ontario in 2026, someone earning $40,000 keeps about 82.0% of gross pay, while someone earning $150,000 keeps about 69.5%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical Ontario paycheque

Across all industries, the median full-time wage in Ontario is $34.62 an hour — about $72,000 a year. After federal tax, Ontario tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$55,099 a year**, or $4,592 a month. That is 76.5% of gross pay.

## Take-home pay in Ontario at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Ontario for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$32,814** | $2,734 | 82.0% |
| $60,000 | **$47,340** | $3,945 | 78.9% |
| $80,000 | **$60,303** | $5,025 | 75.4% |
| $100,000 | **$74,206** | $6,184 | 74.2% |
| $150,000 | **$104,320** | $8,693 | 69.5% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 82.0%; at $150,000 you keep 69.5%.

## What each industry pays in Ontario

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for Ontario, with what each one leaves after Ontario tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Utilities | $56.00/hr | $116,500 | $85,270 |
| Public administration | $48.00/hr | $99,800 | $74,069 |
| Professional, scientific & technical services | $46.15/hr | $96,000 | $71,418 |
| Educational services | $44.18/hr | $91,900 | $68,534 |
| Forestry, fishing, mining, oil & gas | $43.00/hr | $89,400 | $66,775 |
| Finance, insurance & real estate | $41.03/hr | $85,300 | $63,890 |
| Information, culture & recreation | $35.58/hr | $74,000 | $56,262 |
| Construction | $35.19/hr | $73,200 | $55,761 |
| Healthcare & social assistance | $32.91/hr | $68,500 | $52,807 |
| Manufacturing | $30.00/hr | $62,400 | $48,883 |
| Transportation & warehousing | $30.00/hr | $62,400 | $48,883 |
| Other services | $28.00/hr | $58,200 | $46,125 |
| Wholesale & retail trade | $25.64/hr | $53,300 | $42,614 |
| Business & support services | $25.00/hr | $52,000 | $41,641 |
| Agriculture | $23.00/hr | $47,800 | $38,649 |
| Food service & hospitality | $20.00/hr | $41,600 | $34,011 |

The best-paid sector reported here is utilities at $56.00 an hour; the lowest is food service & hospitality at $20.00. That gap — $36.00 an hour — works out to about $74,900 a year before tax.

## How Ontario compares with the rest of Canada

On an $80,000 salary, Ontario ranks **#6 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario ← | $60,303 |

The difference between Ontario and Nunavut, the highest, is $1,996 a year on the same $80,000 salary — about $166 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Ontario

Most Ontario employees are in Toronto, Ottawa, Mississauga, Hamilton and London. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Ontario and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-bc',
    slug: 'bc-take-home-pay-guide-2026',
    title: "British Columbia Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What British Columbia workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in British Columbia is $35.00 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "British Columbia Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "British Columbia's median full-time wage is $35.00/hr. See take-home pay at every salary, wages for every industry, and how British Columbia ranks (#3 of 13) for 2026.",
    keywords: ["British Columbia salary","British Columbia take home pay","British Columbia average salary 2026","British Columbia paycheck calculator","British Columbia income tax 2026","wages in British Columbia"],
    category: 'province',
    tags: ["British Columbia","take-home pay","wages","2026"],
    province: 'British Columbia',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/bc-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in British Columbia is $35.00 an hour, about $72,800 a year, which leaves roughly $56,227 after tax in 2026. On an $80,000 salary, British Columbia ranks #3 of 13 provinces and territories for take-home pay, keeping $61,157.",
    faq: [
          {
                "question": "What is the average salary in British Columbia?",
                "answer": "The median full-time wage in British Columbia is $35.00 an hour, about $72,800 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in British Columbia?",
                "answer": "About $61,157 a year, or $5,096 a month, after federal tax, British Columbia provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does British Columbia have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, British Columbia ranks #3 of 13 provinces and territories for take-home pay in 2026, keeping $61,157. That is $1,142 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in British Columbia?",
                "answer": "Of the sectors Statistics Canada reports for British Columbia, utilities has the highest median full-time wage at $51.63 an hour — roughly $107,400 a year, or $80,531 after tax."
          },
          {
                "question": "How much of my pay do I keep in British Columbia?",
                "answer": "It depends on the salary. In British Columbia in 2026, someone earning $40,000 keeps about 83.3% of gross pay, while someone earning $150,000 keeps about 71.6%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical British Columbia paycheque

Across all industries, the median full-time wage in British Columbia is $35.00 an hour — about $72,800 a year. After federal tax, British Columbia tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$56,227 a year**, or $4,686 a month. That is 77.2% of gross pay.

## Take-home pay in British Columbia at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in British Columbia for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$33,333** | $2,778 | 83.3% |
| $60,000 | **$47,755** | $3,980 | 79.6% |
| $80,000 | **$61,157** | $5,096 | 76.4% |
| $100,000 | **$75,373** | $6,281 | 75.4% |
| $150,000 | **$107,377** | $8,948 | 71.6% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 83.3%; at $150,000 you keep 71.6%.

## What each industry pays in British Columbia

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for British Columbia, with what each one leaves after British Columbia tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Utilities | $51.63/hr | $107,400 | $80,531 |
| Forestry, fishing, mining, oil & gas | $45.00/hr | $93,600 | $70,778 |
| Public administration | $45.00/hr | $93,600 | $70,778 |
| Professional, scientific & technical services | $43.78/hr | $91,100 | $68,983 |
| Educational services | $40.00/hr | $83,200 | $63,363 |
| Information, culture & recreation | $38.46/hr | $80,000 | $61,157 |
| Finance, insurance & real estate | $38.00/hr | $79,000 | $60,468 |
| Construction | $37.50/hr | $78,000 | $59,778 |
| Manufacturing | $35.00/hr | $72,800 | $56,227 |
| Transportation & warehousing | $34.00/hr | $70,700 | $54,818 |
| Healthcare & social assistance | $33.33/hr | $69,300 | $53,878 |
| Other services | $30.00/hr | $62,400 | $49,334 |
| Business & support services | $27.50/hr | $57,200 | $45,791 |
| Wholesale & retail trade | $26.44/hr | $55,000 | $44,203 |
| Agriculture | $25.00/hr | $52,000 | $42,036 |
| Food service & hospitality | $22.00/hr | $45,800 | $37,453 |

The best-paid sector reported here is utilities at $51.63 an hour; the lowest is food service & hospitality at $22.00. That gap — $29.63 an hour — works out to about $61,600 a year before tax.

## How British Columbia compares with the rest of Canada

On an $80,000 salary, British Columbia ranks **#3 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia ← | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between British Columbia and Nunavut, the highest, is $1,142 a year on the same $80,000 salary — about $95 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in British Columbia

Most British Columbia employees are in Vancouver, Surrey, Burnaby, Victoria and Kelowna. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for British Columbia and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-alberta',
    slug: 'alberta-take-home-pay-guide-2026',
    title: "Alberta Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Alberta workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in Alberta is $34.97 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "Alberta Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "Alberta's median full-time wage is $34.97/hr. See take-home pay at every salary, wages for every industry, and how Alberta ranks (#5 of 13) for 2026.",
    keywords: ["Alberta salary","Alberta take home pay","Alberta average salary 2026","Alberta paycheck calculator","Alberta income tax 2026","wages in Alberta"],
    category: 'province',
    tags: ["Alberta","take-home pay","wages","2026"],
    province: 'Alberta',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/alberta-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in Alberta is $34.97 an hour, about $72,700 a year, which leaves roughly $55,861 after tax in 2026. On an $80,000 salary, Alberta ranks #5 of 13 provinces and territories for take-home pay, keeping $60,698.",
    faq: [
          {
                "question": "What is the average salary in Alberta?",
                "answer": "The median full-time wage in Alberta is $34.97 an hour, about $72,700 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in Alberta?",
                "answer": "About $60,698 a year, or $5,058 a month, after federal tax, Alberta provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Alberta have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Alberta ranks #5 of 13 provinces and territories for take-home pay in 2026, keeping $60,698. That is $1,601 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Alberta?",
                "answer": "Of the sectors Statistics Canada reports for Alberta, utilities has the highest median full-time wage at $56.00 an hour — roughly $116,500 a year, or $85,926 after tax."
          },
          {
                "question": "How much of my pay do I keep in Alberta?",
                "answer": "It depends on the salary. In Alberta in 2026, someone earning $40,000 keeps about 83.3% of gross pay, while someone earning $150,000 keeps about 71.6%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical Alberta paycheque

Across all industries, the median full-time wage in Alberta is $34.97 an hour — about $72,700 a year. After federal tax, Alberta tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$55,861 a year**, or $4,655 a month. That is 76.8% of gross pay.

## Take-home pay in Alberta at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Alberta for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$33,332** | $2,778 | 83.3% |
| $60,000 | **$47,691** | $3,974 | 79.5% |
| $80,000 | **$60,698** | $5,058 | 75.9% |
| $100,000 | **$74,459** | $6,205 | 74.5% |
| $150,000 | **$107,458** | $8,955 | 71.6% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 83.3%; at $150,000 you keep 71.6%.

## What each industry pays in Alberta

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for Alberta, with what each one leaves after Alberta tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Utilities | $56.00/hr | $116,500 | $85,926 |
| Forestry, fishing, mining, oil & gas | $52.88/hr | $110,000 | $81,409 |
| Public administration | $45.67/hr | $95,000 | $70,984 |
| Professional, scientific & technical services | $41.81/hr | $87,000 | $65,424 |
| Educational services | $40.46/hr | $84,200 | $63,500 |
| Finance, insurance & real estate | $38.15/hr | $79,400 | $60,297 |
| Construction | $37.00/hr | $77,000 | $58,696 |
| Transportation & warehousing | $34.20/hr | $71,100 | $54,822 |
| Manufacturing | $32.00/hr | $66,600 | $51,928 |
| Healthcare & social assistance | $30.00/hr | $62,400 | $49,254 |
| Information, culture & recreation | $30.00/hr | $62,400 | $49,254 |
| Agriculture | $29.10/hr | $60,500 | $48,019 |
| Other services | $28.85/hr | $60,000 | $47,691 |
| Wholesale & retail trade | $26.92/hr | $56,000 | $44,866 |
| Business & support services | $25.26/hr | $52,500 | $42,343 |
| Food service & hospitality | $18.00/hr | $37,400 | $31,458 |

The best-paid sector reported here is utilities at $56.00 an hour; the lowest is food service & hospitality at $18.00. That gap — $38.00 an hour — works out to about $79,000 a year before tax.

## How Alberta compares with the rest of Canada

On an $80,000 salary, Alberta ranks **#5 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta ← | $60,698 |
| 6 | Ontario | $60,303 |

The difference between Alberta and Nunavut, the highest, is $1,601 a year on the same $80,000 salary — about $133 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Alberta

Most Alberta employees are in Calgary, Edmonton, Red Deer and Lethbridge. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Alberta and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-quebec',
    slug: 'quebec-take-home-pay-guide-2026',
    title: "Quebec Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Quebec workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in Quebec is $33.00 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "Quebec Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "Quebec's median full-time wage is $33.00/hr. See take-home pay at every salary, wages for every industry, and how Quebec ranks (#11 of 13) for 2026.",
    keywords: ["Quebec salary","Quebec take home pay","Quebec average salary 2026","Quebec paycheck calculator","Quebec income tax 2026","wages in Quebec"],
    category: 'province',
    tags: ["Quebec","take-home pay","wages","2026"],
    province: 'Quebec',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/quebec-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in Quebec is $33.00 an hour, about $68,600 a year, which leaves roughly $50,566 after tax in 2026. On an $80,000 salary, Quebec ranks #11 of 13 provinces and territories for take-home pay, keeping $57,390.",
    faq: [
          {
                "question": "What is the average salary in Quebec?",
                "answer": "The median full-time wage in Quebec is $33.00 an hour, about $68,600 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in Quebec?",
                "answer": "About $57,390 a year, or $4,782 a month, after federal tax, Quebec provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Quebec have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Quebec ranks #11 of 13 provinces and territories for take-home pay in 2026, keeping $57,390. That is $4,909 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Quebec?",
                "answer": "Of the sectors Statistics Canada reports for Quebec, utilities has the highest median full-time wage at $53.11 an hour — roughly $110,500 a year, or $76,624 after tax."
          },
          {
                "question": "How much of my pay do I keep in Quebec?",
                "answer": "It depends on the salary. In Quebec in 2026, someone earning $40,000 keeps about 80.6% of gross pay, while someone earning $150,000 keeps about 65.4%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical Quebec paycheque

Across all industries, the median full-time wage in Quebec is $33.00 an hour — about $68,600 a year. After federal tax, Quebec tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$50,566 a year**, or $4,214 a month. That is 73.7% of gross pay.

## Take-home pay in Quebec at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Quebec for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$32,229** | $2,686 | 80.6% |
| $60,000 | **$45,581** | $3,798 | 76.0% |
| $80,000 | **$57,390** | $4,782 | 71.7% |
| $100,000 | **$69,963** | $5,830 | 70.0% |
| $150,000 | **$98,130** | $8,178 | 65.4% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 80.6%; at $150,000 you keep 65.4%.

## What each industry pays in Quebec

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for Quebec, with what each one leaves after Quebec tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Utilities | $53.11/hr | $110,500 | $76,624 |
| Educational services | $43.79/hr | $91,100 | $64,311 |
| Public administration | $42.00/hr | $87,400 | $61,961 |
| Forestry, fishing, mining, oil & gas | $40.00/hr | $83,200 | $59,340 |
| Professional, scientific & technical services | $40.00/hr | $83,200 | $59,340 |
| Finance, insurance & real estate | $38.46/hr | $80,000 | $57,390 |
| Construction | $38.00/hr | $79,000 | $56,780 |
| Information, culture & recreation | $35.00/hr | $72,800 | $53,038 |
| Manufacturing | $31.61/hr | $65,700 | $48,885 |
| Other services | $30.00/hr | $62,400 | $46,972 |
| Healthcare & social assistance | $29.00/hr | $60,300 | $45,755 |
| Transportation & warehousing | $29.00/hr | $60,300 | $45,755 |
| Business & support services | $25.00/hr | $52,000 | $40,423 |
| Wholesale & retail trade | $25.00/hr | $52,000 | $40,423 |
| Agriculture | $24.00/hr | $49,900 | $38,989 |
| Food service & hospitality | $21.00/hr | $43,700 | $34,755 |

The best-paid sector reported here is utilities at $53.11 an hour; the lowest is food service & hospitality at $21.00. That gap — $32.11 an hour — works out to about $66,800 a year before tax.

## How Quebec compares with the rest of Canada

On an $80,000 salary, Quebec ranks **#11 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between Quebec and Nunavut, the highest, is $4,909 a year on the same $80,000 salary — about $409 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Quebec

Most Quebec employees are in Montreal, Quebec City, Laval and Gatineau. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Quebec and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-manitoba',
    slug: 'manitoba-take-home-pay-guide-2026',
    title: "Manitoba Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Manitoba workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in Manitoba is $28.74 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "Manitoba Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "Manitoba's median full-time wage is $28.74/hr. See take-home pay at every salary, wages for every industry, and how Manitoba ranks (#9 of 13) for 2026.",
    keywords: ["Manitoba salary","Manitoba take home pay","Manitoba average salary 2026","Manitoba paycheck calculator","Manitoba income tax 2026","wages in Manitoba"],
    category: 'province',
    tags: ["Manitoba","take-home pay","wages","2026"],
    province: 'Manitoba',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/manitoba-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in Manitoba is $28.74 an hour, about $59,800 a year, which leaves roughly $45,650 after tax in 2026. On an $80,000 salary, Manitoba ranks #9 of 13 provinces and territories for take-home pay, keeping $58,228.",
    faq: [
          {
                "question": "What is the average salary in Manitoba?",
                "answer": "The median full-time wage in Manitoba is $28.74 an hour, about $59,800 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in Manitoba?",
                "answer": "About $58,228 a year, or $4,852 a month, after federal tax, Manitoba provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Manitoba have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Manitoba ranks #9 of 13 provinces and territories for take-home pay in 2026, keeping $58,228. That is $4,071 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Manitoba?",
                "answer": "Of the sectors Statistics Canada reports for Manitoba, utilities has the highest median full-time wage at $46.15 an hour — roughly $96,000 a year, or $68,775 after tax."
          },
          {
                "question": "How much of my pay do I keep in Manitoba?",
                "answer": "It depends on the salary. In Manitoba in 2026, someone earning $40,000 keeps about 80.4% of gross pay, while someone earning $150,000 keeps about 67.2%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical Manitoba paycheque

Across all industries, the median full-time wage in Manitoba is $28.74 an hour — about $59,800 a year. After federal tax, Manitoba tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$45,650 a year**, or $3,804 a month. That is 76.3% of gross pay.

## Take-home pay in Manitoba at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Manitoba for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$32,174** | $2,681 | 80.4% |
| $60,000 | **$45,772** | $3,814 | 76.3% |
| $80,000 | **$58,228** | $4,852 | 72.8% |
| $100,000 | **$71,445** | $5,954 | 71.4% |
| $150,000 | **$100,797** | $8,400 | 67.2% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 80.4%; at $150,000 you keep 67.2%.

## What each industry pays in Manitoba

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for Manitoba, with what each one leaves after Manitoba tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Utilities | $46.15/hr | $96,000 | $68,775 |
| Forestry, fishing, mining, oil & gas | $43.00/hr | $89,400 | $64,369 |
| Public administration | $41.36/hr | $86,000 | $62,100 |
| Educational services | $35.38/hr | $73,600 | $54,144 |
| Professional, scientific & technical services | $35.00/hr | $72,800 | $53,645 |
| Finance, insurance & real estate | $32.97/hr | $68,600 | $51,030 |
| Construction | $30.00/hr | $62,400 | $47,240 |
| Transportation & warehousing | $28.75/hr | $59,800 | $45,650 |
| Information, culture & recreation | $27.97/hr | $58,200 | $44,615 |
| Manufacturing | $27.00/hr | $56,200 | $43,264 |
| Healthcare & social assistance | $27.00/hr | $56,200 | $43,264 |
| Other services | $24.25/hr | $50,400 | $39,345 |
| Agriculture | $24.00/hr | $49,900 | $39,007 |
| Wholesale & retail trade | $24.00/hr | $49,900 | $39,007 |
| Business & support services | $21.00/hr | $43,700 | $34,746 |
| Food service & hospitality | $17.00/hr | $35,400 | $28,977 |

The best-paid sector reported here is utilities at $46.15 an hour; the lowest is food service & hospitality at $17.00. That gap — $29.15 an hour — works out to about $60,600 a year before tax.

## How Manitoba compares with the rest of Canada

On an $80,000 salary, Manitoba ranks **#9 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between Manitoba and Nunavut, the highest, is $4,071 a year on the same $80,000 salary — about $339 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Manitoba

Most Manitoba employees are in Winnipeg, Brandon and Steinbach. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Manitoba and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-saskatchewan',
    slug: 'saskatchewan-take-home-pay-guide-2026',
    title: "Saskatchewan Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Saskatchewan workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in Saskatchewan is $31.25 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "Saskatchewan Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "Saskatchewan's median full-time wage is $31.25/hr. See take-home pay at every salary, wages for every industry, and how Saskatchewan ranks (#7 of 13) for 2026.",
    keywords: ["Saskatchewan salary","Saskatchewan take home pay","Saskatchewan average salary 2026","Saskatchewan paycheck calculator","Saskatchewan income tax 2026","wages in Saskatchewan"],
    category: 'province',
    tags: ["Saskatchewan","take-home pay","wages","2026"],
    province: 'Saskatchewan',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/saskatchewan-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in Saskatchewan is $31.25 an hour, about $65,000 a year, which leaves roughly $49,588 after tax in 2026. On an $80,000 salary, Saskatchewan ranks #7 of 13 provinces and territories for take-home pay, keeping $59,022.",
    faq: [
          {
                "question": "What is the average salary in Saskatchewan?",
                "answer": "The median full-time wage in Saskatchewan is $31.25 an hour, about $65,000 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in Saskatchewan?",
                "answer": "About $59,022 a year, or $4,918 a month, after federal tax, Saskatchewan provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Saskatchewan have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Saskatchewan ranks #7 of 13 provinces and territories for take-home pay in 2026, keeping $59,022. That is $3,277 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Saskatchewan?",
                "answer": "Of the sectors Statistics Canada reports for Saskatchewan, forestry, fishing, mining, oil & gas has the highest median full-time wage at $50.00 an hour — roughly $104,000 a year, or $74,968 after tax."
          },
          {
                "question": "How much of my pay do I keep in Saskatchewan?",
                "answer": "It depends on the salary. In Saskatchewan in 2026, someone earning $40,000 keeps about 81.8% of gross pay, while someone earning $150,000 keeps about 69.4%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical Saskatchewan paycheque

Across all industries, the median full-time wage in Saskatchewan is $31.25 an hour — about $65,000 a year. After federal tax, Saskatchewan tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$49,588 a year**, or $4,132 a month. That is 76.3% of gross pay.

## Take-home pay in Saskatchewan at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Saskatchewan for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$32,721** | $2,727 | 81.8% |
| $60,000 | **$46,520** | $3,877 | 77.5% |
| $80,000 | **$59,022** | $4,918 | 73.8% |
| $100,000 | **$72,288** | $6,024 | 72.3% |
| $150,000 | **$104,037** | $8,670 | 69.4% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 81.8%; at $150,000 you keep 69.4%.

## What each industry pays in Saskatchewan

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for Saskatchewan, with what each one leaves after Saskatchewan tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Forestry, fishing, mining, oil & gas | $50.00/hr | $104,000 | $74,968 |
| Utilities | $46.00/hr | $95,700 | $69,407 |
| Public administration | $42.00/hr | $87,400 | $63,846 |
| Educational services | $39.23/hr | $81,600 | $60,051 |
| Professional, scientific & technical services | $38.46/hr | $80,000 | $59,022 |
| Finance, insurance & real estate | $33.85/hr | $70,400 | $52,920 |
| Manufacturing | $32.66/hr | $67,900 | $51,367 |
| Construction | $32.00/hr | $66,600 | $50,569 |
| Information, culture & recreation | $31.50/hr | $65,500 | $49,894 |
| Transportation & warehousing | $30.00/hr | $62,400 | $47,992 |
| Healthcare & social assistance | $28.05/hr | $58,300 | $45,426 |
| Agriculture | $28.00/hr | $58,200 | $45,359 |
| Other services | $27.50/hr | $57,200 | $44,681 |
| Wholesale & retail trade | $24.61/hr | $51,200 | $40,537 |
| Business & support services | $21.00/hr | $43,700 | $35,303 |
| Food service & hospitality | $17.00/hr | $35,400 | $29,512 |

The best-paid sector reported here is forestry, fishing, mining, oil & gas at $50.00 an hour; the lowest is food service & hospitality at $17.00. That gap — $33.00 an hour — works out to about $68,600 a year before tax.

## How Saskatchewan compares with the rest of Canada

On an $80,000 salary, Saskatchewan ranks **#7 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between Saskatchewan and Nunavut, the highest, is $3,277 a year on the same $80,000 salary — about $273 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Saskatchewan

Most Saskatchewan employees are in Saskatoon, Regina and Prince Albert. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Saskatchewan and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-nova-scotia',
    slug: 'nova-scotia-take-home-pay-guide-2026',
    title: "Nova Scotia Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Nova Scotia workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in Nova Scotia is $29.80 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "Nova Scotia Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "Nova Scotia's median full-time wage is $29.80/hr. See take-home pay at every salary, wages for every industry, and how Nova Scotia ranks (#13 of 13) for 2026.",
    keywords: ["Nova Scotia salary","Nova Scotia take home pay","Nova Scotia average salary 2026","Nova Scotia paycheck calculator","Nova Scotia income tax 2026","wages in Nova Scotia"],
    category: 'province',
    tags: ["Nova Scotia","take-home pay","wages","2026"],
    province: 'Nova Scotia',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/nova-scotia-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in Nova Scotia is $29.80 an hour, about $62,000 a year, which leaves roughly $45,903 after tax in 2026. On an $80,000 salary, Nova Scotia ranks #13 of 13 provinces and territories for take-home pay, keeping $56,439.",
    faq: [
          {
                "question": "What is the average salary in Nova Scotia?",
                "answer": "The median full-time wage in Nova Scotia is $29.80 an hour, about $62,000 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in Nova Scotia?",
                "answer": "About $56,439 a year, or $4,703 a month, after federal tax, Nova Scotia provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Nova Scotia have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Nova Scotia ranks #13 of 13 provinces and territories for take-home pay in 2026, keeping $56,439. That is $5,860 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Nova Scotia?",
                "answer": "Of the sectors Statistics Canada reports for Nova Scotia, utilities has the highest median full-time wage at $45.05 an hour — roughly $93,700 a year, or $64,921 after tax."
          },
          {
                "question": "How much of my pay do I keep in Nova Scotia?",
                "answer": "It depends on the salary. In Nova Scotia in 2026, someone earning $40,000 keeps about 79.3% of gross pay, while someone earning $150,000 keeps about 65.4%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical Nova Scotia paycheque

Across all industries, the median full-time wage in Nova Scotia is $29.80 an hour — about $62,000 a year. After federal tax, Nova Scotia tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$45,903 a year**, or $3,825 a month. That is 74.0% of gross pay.

## Take-home pay in Nova Scotia at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Nova Scotia for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$31,734** | $2,644 | 79.3% |
| $60,000 | **$44,726** | $3,727 | 74.5% |
| $80,000 | **$56,439** | $4,703 | 70.5% |
| $100,000 | **$68,867** | $5,739 | 68.9% |
| $150,000 | **$98,117** | $8,176 | 65.4% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 79.3%; at $150,000 you keep 65.4%.

## What each industry pays in Nova Scotia

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for Nova Scotia, with what each one leaves after Nova Scotia tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Utilities | $45.05/hr | $93,700 | $64,921 |
| Public administration | $41.21/hr | $85,700 | $59,895 |
| Educational services | $39.42/hr | $82,000 | $57,645 |
| Professional, scientific & technical services | $38.46/hr | $80,000 | $56,439 |
| Finance, insurance & real estate | $32.05/hr | $66,700 | $48,597 |
| Healthcare & social assistance | $32.00/hr | $66,600 | $48,540 |
| Information, culture & recreation | $29.00/hr | $60,300 | $44,903 |
| Transportation & warehousing | $28.85/hr | $60,000 | $44,726 |
| Construction | $28.21/hr | $58,700 | $43,937 |
| Manufacturing | $28.00/hr | $58,200 | $43,611 |
| Other services | $27.00/hr | $56,200 | $42,306 |
| Forestry, fishing, mining, oil & gas | $25.00/hr | $52,000 | $39,565 |
| Wholesale & retail trade | $22.00/hr | $45,800 | $35,519 |
| Business & support services | $21.00/hr | $43,700 | $34,148 |
| Agriculture | $20.00/hr | $41,600 | $32,778 |
| Food service & hospitality | $18.00/hr | $37,400 | $30,037 |

The best-paid sector reported here is utilities at $45.05 an hour; the lowest is food service & hospitality at $18.00. That gap — $27.05 an hour — works out to about $56,300 a year before tax.

## How Nova Scotia compares with the rest of Canada

On an $80,000 salary, Nova Scotia ranks **#13 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between Nova Scotia and Nunavut, the highest, is $5,860 a year on the same $80,000 salary — about $488 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Nova Scotia

Most Nova Scotia employees are in Halifax, Sydney and Truro. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Nova Scotia and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-new-brunswick',
    slug: 'new-brunswick-take-home-pay-guide-2026',
    title: "New Brunswick Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What New Brunswick workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in New Brunswick is $28.85 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "New Brunswick Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "New Brunswick's median full-time wage is $28.85/hr. See take-home pay at every salary, wages for every industry, and how New Brunswick ranks (#8 of 13) for 2026.",
    keywords: ["New Brunswick salary","New Brunswick take home pay","New Brunswick average salary 2026","New Brunswick paycheck calculator","New Brunswick income tax 2026","wages in New Brunswick"],
    category: 'province',
    tags: ["New Brunswick","take-home pay","wages","2026"],
    province: 'New Brunswick',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/new-brunswick-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in New Brunswick is $28.85 an hour, about $60,000 a year, which leaves roughly $46,048 after tax in 2026. On an $80,000 salary, New Brunswick ranks #8 of 13 provinces and territories for take-home pay, keeping $58,246.",
    faq: [
          {
                "question": "What is the average salary in New Brunswick?",
                "answer": "The median full-time wage in New Brunswick is $28.85 an hour, about $60,000 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in New Brunswick?",
                "answer": "About $58,246 a year, or $4,854 a month, after federal tax, New Brunswick provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does New Brunswick have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, New Brunswick ranks #8 of 13 provinces and territories for take-home pay in 2026, keeping $58,246. That is $4,053 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in New Brunswick?",
                "answer": "Of the sectors Statistics Canada reports for New Brunswick, utilities has the highest median full-time wage at $46.15 an hour — roughly $96,000 a year, or $68,595 after tax."
          },
          {
                "question": "How much of my pay do I keep in New Brunswick?",
                "answer": "It depends on the salary. In New Brunswick in 2026, someone earning $40,000 keeps about 80.7% of gross pay, while someone earning $150,000 keeps about 67.6%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical New Brunswick paycheque

Across all industries, the median full-time wage in New Brunswick is $28.85 an hour — about $60,000 a year. After federal tax, New Brunswick tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$46,048 a year**, or $3,837 a month. That is 76.7% of gross pay.

## Take-home pay in New Brunswick at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in New Brunswick for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$32,275** | $2,690 | 80.7% |
| $60,000 | **$46,048** | $3,837 | 76.7% |
| $80,000 | **$58,246** | $4,854 | 72.8% |
| $100,000 | **$71,215** | $5,935 | 71.2% |
| $150,000 | **$101,330** | $8,444 | 67.6% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 80.7%; at $150,000 you keep 67.6%.

## What each industry pays in New Brunswick

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for New Brunswick, with what each one leaves after New Brunswick tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Utilities | $46.15/hr | $96,000 | $68,595 |
| Public administration | $39.00/hr | $81,100 | $58,937 |
| Professional, scientific & technical services | $34.00/hr | $70,700 | $52,469 |
| Educational services | $33.65/hr | $70,000 | $52,042 |
| Finance, insurance & real estate | $30.00/hr | $62,400 | $47,483 |
| Information, culture & recreation | $29.00/hr | $60,300 | $46,227 |
| Construction | $28.85/hr | $60,000 | $46,048 |
| Forestry, fishing, mining, oil & gas | $28.46/hr | $59,200 | $45,569 |
| Healthcare & social assistance | $28.41/hr | $59,100 | $45,509 |
| Transportation & warehousing | $26.44/hr | $55,000 | $42,795 |
| Manufacturing | $26.11/hr | $54,300 | $42,331 |
| Other services | $26.00/hr | $54,100 | $42,199 |
| Wholesale & retail trade | $22.50/hr | $46,800 | $37,089 |
| Business & support services | $22.00/hr | $45,800 | $36,381 |
| Agriculture | $21.00/hr | $43,700 | $34,894 |
| Food service & hospitality | $18.00/hr | $37,400 | $30,434 |

The best-paid sector reported here is utilities at $46.15 an hour; the lowest is food service & hospitality at $18.00. That gap — $28.15 an hour — works out to about $58,600 a year before tax.

## How New Brunswick compares with the rest of Canada

On an $80,000 salary, New Brunswick ranks **#8 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between New Brunswick and Nunavut, the highest, is $4,053 a year on the same $80,000 salary — about $338 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in New Brunswick

Most New Brunswick employees are in Moncton, Saint John and Fredericton. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for New Brunswick and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-newfoundland',
    slug: 'newfoundland-take-home-pay-guide-2026',
    title: "Newfoundland and Labrador Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Newfoundland and Labrador workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in Newfoundland and Labrador is $30.07 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "Newfoundland and Labrador Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "Newfoundland and Labrador's median full-time wage is $30.07/hr. See take-home pay at every salary, wages for every industry, and how Newfoundland and Labrador ranks (#10 of 13) for 2026.",
    keywords: ["Newfoundland and Labrador salary","Newfoundland and Labrador take home pay","Newfoundland and Labrador average salary 2026","Newfoundland and Labrador paycheck calculator","Newfoundland and Labrador income tax 2026","wages in Newfoundland and Labrador"],
    category: 'province',
    tags: ["Newfoundland and Labrador","take-home pay","wages","2026"],
    province: 'Newfoundland and Labrador',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/newfoundland-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in Newfoundland and Labrador is $30.07 an hour, about $62,500 a year, which leaves roughly $47,244 after tax in 2026. On an $80,000 salary, Newfoundland and Labrador ranks #10 of 13 provinces and territories for take-home pay, keeping $57,857.",
    faq: [
          {
                "question": "What is the average salary in Newfoundland and Labrador?",
                "answer": "The median full-time wage in Newfoundland and Labrador is $30.07 an hour, about $62,500 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in Newfoundland and Labrador?",
                "answer": "About $57,857 a year, or $4,821 a month, after federal tax, Newfoundland and Labrador provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Newfoundland and Labrador have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Newfoundland and Labrador ranks #10 of 13 provinces and territories for take-home pay in 2026, keeping $57,857. That is $4,442 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Newfoundland and Labrador?",
                "answer": "Of the sectors Statistics Canada reports for Newfoundland and Labrador, utilities has the highest median full-time wage at $51.00 an hour — roughly $106,100 a year, or $74,489 after tax."
          },
          {
                "question": "How much of my pay do I keep in Newfoundland and Labrador?",
                "answer": "It depends on the salary. In Newfoundland and Labrador in 2026, someone earning $40,000 keeps about 81.0% of gross pay, while someone earning $150,000 keeps about 67.1%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical Newfoundland and Labrador paycheque

Across all industries, the median full-time wage in Newfoundland and Labrador is $30.07 an hour — about $62,500 a year. After federal tax, Newfoundland and Labrador tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$47,244 a year**, or $3,937 a month. That is 75.6% of gross pay.

## Take-home pay in Newfoundland and Labrador at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Newfoundland and Labrador for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$32,390** | $2,699 | 81.0% |
| $60,000 | **$45,763** | $3,814 | 76.3% |
| $80,000 | **$57,857** | $4,821 | 72.3% |
| $100,000 | **$70,603** | $5,884 | 70.6% |
| $150,000 | **$100,702** | $8,392 | 67.1% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 81.0%; at $150,000 you keep 67.1%.

## What each industry pays in Newfoundland and Labrador

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for Newfoundland and Labrador, with what each one leaves after Newfoundland and Labrador tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Utilities | $51.00/hr | $106,100 | $74,489 |
| Forestry, fishing, mining, oil & gas | $50.00/hr | $104,000 | $73,151 |
| Educational services | $40.87/hr | $85,000 | $60,977 |
| Professional, scientific & technical services | $39.38/hr | $81,900 | $59,042 |
| Public administration | $38.46/hr | $80,000 | $57,857 |
| Finance, insurance & real estate | $30.77/hr | $64,000 | $48,133 |
| Construction | $30.40/hr | $63,200 | $47,659 |
| Transportation & warehousing | $30.00/hr | $62,400 | $47,185 |
| Information, culture & recreation | $30.00/hr | $62,400 | $47,185 |
| Healthcare & social assistance | $28.85/hr | $60,000 | $45,763 |
| Manufacturing | $26.00/hr | $54,100 | $41,946 |
| Other services | $25.00/hr | $52,000 | $40,566 |
| Business & support services | $22.51/hr | $46,800 | $37,150 |
| Wholesale & retail trade | $21.40/hr | $44,500 | $35,605 |
| Agriculture | $21.37/hr | $44,400 | $35,533 |
| Food service & hospitality | $17.75/hr | $36,900 | $30,175 |

The best-paid sector reported here is utilities at $51.00 an hour; the lowest is food service & hospitality at $17.75. That gap — $33.25 an hour — works out to about $69,200 a year before tax.

## How Newfoundland and Labrador compares with the rest of Canada

On an $80,000 salary, Newfoundland and Labrador ranks **#10 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between Newfoundland and Labrador and Nunavut, the highest, is $4,442 a year on the same $80,000 salary — about $370 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Newfoundland and Labrador

Most Newfoundland and Labrador employees are in St. John's, Mount Pearl and Corner Brook. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Newfoundland and Labrador and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-pei',
    slug: 'pei-take-home-pay-guide-2026',
    title: "Prince Edward Island Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Prince Edward Island workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "The median full-time wage in Prince Edward Island is $28.21 an hour. Here is what that, and every other salary level, leaves after 2026 tax — with Statistics Canada wage data for every industry.",
    metaTitle: "Prince Edward Island Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "Prince Edward Island's median full-time wage is $28.21/hr. See take-home pay at every salary, wages for every industry, and how Prince Edward Island ranks (#12 of 13) for 2026.",
    keywords: ["Prince Edward Island salary","Prince Edward Island take home pay","Prince Edward Island average salary 2026","Prince Edward Island paycheck calculator","Prince Edward Island income tax 2026","wages in Prince Edward Island"],
    category: 'province',
    tags: ["Prince Edward Island","take-home pay","wages","2026"],
    province: 'Prince Edward Island',
    publishedAt: '2026-08-08',
    readTime: 8,
    imageUrl: '/blog/pei-take-home-pay-guide-2026.png',
    directAnswer: "The median full-time wage in Prince Edward Island is $28.21 an hour, about $58,700 a year, which leaves roughly $44,638 after tax in 2026. On an $80,000 salary, Prince Edward Island ranks #12 of 13 provinces and territories for take-home pay, keeping $57,335.",
    faq: [
          {
                "question": "What is the average salary in Prince Edward Island?",
                "answer": "The median full-time wage in Prince Edward Island is $28.21 an hour, about $58,700 a year before tax, according to Statistics Canada's 2025 employee wage data. Median means half of full-time workers earn more and half earn less — a more useful number than an average, which a small number of very high earners can distort."
          },
          {
                "question": "What is the take-home pay on $80,000 in Prince Edward Island?",
                "answer": "About $57,335 a year, or $4,778 a month, after federal tax, Prince Edward Island provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Prince Edward Island have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Prince Edward Island ranks #12 of 13 provinces and territories for take-home pay in 2026, keeping $57,335. That is $4,964 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Prince Edward Island?",
                "answer": "Of the sectors Statistics Canada reports for Prince Edward Island, utilities has the highest median full-time wage at $43.27 an hour — roughly $90,000 a year, or $63,499 after tax."
          },
          {
                "question": "How much of my pay do I keep in Prince Edward Island?",
                "answer": "It depends on the salary. In Prince Edward Island in 2026, someone earning $40,000 keeps about 80.4% of gross pay, while someone earning $150,000 keeps about 66.0%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `## The typical Prince Edward Island paycheque

Across all industries, the median full-time wage in Prince Edward Island is $28.21 an hour — about $58,700 a year. After federal tax, Prince Edward Island tax, CPP/CPP2 and EI, a single employee on that salary keeps roughly **$44,638 a year**, or $3,720 a month. That is 76.0% of gross pay.

## Take-home pay in Prince Edward Island at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Prince Edward Island for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$32,152** | $2,679 | 80.4% |
| $60,000 | **$45,447** | $3,787 | 75.7% |
| $80,000 | **$57,335** | $4,778 | 71.7% |
| $100,000 | **$69,789** | $5,816 | 69.8% |
| $150,000 | **$98,973** | $8,248 | 66.0% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 80.4%; at $150,000 you keep 66.0%.

## What each industry pays in Prince Edward Island

Statistics Canada publishes the median wage of full-time employees by industry. Here is every sector it reports for Prince Edward Island, with what each one leaves after Prince Edward Island tax, federal tax, CPP and EI in 2026.

| Industry | Median wage | ≈ Annual | Take-home |
| --- | --- | --- | --- |
| Utilities | $43.27/hr | $90,000 | $63,499 |
| Public administration | $39.49/hr | $82,100 | $58,603 |
| Professional, scientific & technical services | $35.65/hr | $74,200 | $53,840 |
| Educational services | $34.62/hr | $72,000 | $52,554 |
| Healthcare & social assistance | $32.00/hr | $66,600 | $49,424 |
| Finance, insurance & real estate | $29.47/hr | $61,300 | $46,231 |
| Construction | $28.00/hr | $58,200 | $44,304 |
| Transportation & warehousing | $26.00/hr | $54,100 | $41,566 |
| Manufacturing | $24.00/hr | $49,900 | $38,762 |
| Forestry, fishing, mining, oil & gas | $22.61/hr | $47,000 | $36,826 |
| Information, culture & recreation | $22.00/hr | $45,800 | $36,024 |
| Other services | $22.00/hr | $45,800 | $36,024 |
| Wholesale & retail trade | $21.00/hr | $43,700 | $34,622 |
| Business & support services | $20.00/hr | $41,600 | $33,220 |
| Agriculture | $20.00/hr | $41,600 | $33,220 |
| Food service & hospitality | $18.00/hr | $37,400 | $30,416 |

The best-paid sector reported here is utilities at $43.27 an hour; the lowest is food service & hospitality at $18.00. That gap — $25.27 an hour — works out to about $52,600 a year before tax.

## How Prince Edward Island compares with the rest of Canada

On an $80,000 salary, Prince Edward Island ranks **#12 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between Prince Edward Island and Nunavut, the highest, is $4,964 a year on the same $80,000 salary — about $414 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Prince Edward Island

Most Prince Edward Island employees are in Charlottetown and Summerside. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Prince Edward Island and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-yukon',
    slug: 'yukon-take-home-pay-guide-2026',
    title: "Yukon Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Yukon workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "What salaries in Yukon leave after federal and territorial tax, CPP and EI in 2026, and how the territory compares with the rest of Canada.",
    metaTitle: "Yukon Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "See take-home pay at every salary level in Yukon for 2026, and how it ranks (#4 of 13) against every other province and territory.",
    keywords: ["Yukon salary","Yukon take home pay","Yukon average salary 2026","Yukon paycheck calculator","Yukon income tax 2026","wages in Yukon"],
    category: 'province',
    tags: ["Yukon","take-home pay","wages","2026"],
    province: 'Yukon',
    publishedAt: '2026-08-08',
    readTime: 6,
    imageUrl: '/blog/yukon-take-home-pay-guide-2026.png',
    directAnswer: "On an $80,000 salary, Yukon ranks #4 of 13 provinces and territories for take-home pay in 2026, keeping $61,039 after federal tax, territorial tax, CPP and EI.",
    faq: [
          {
                "question": "What is the average salary in Yukon?",
                "answer": "Statistics Canada does not publish a median wage for Yukon in its industry wage table, so this guide does not estimate one."
          },
          {
                "question": "What is the take-home pay on $80,000 in Yukon?",
                "answer": "About $61,039 a year, or $5,087 a month, after federal tax, Yukon provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Yukon have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Yukon ranks #4 of 13 provinces and territories for take-home pay in 2026, keeping $61,039. That is $1,260 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Yukon?",
                "answer": "Statistics Canada does not publish industry wage medians for Yukon."
          },
          {
                "question": "How much of my pay do I keep in Yukon?",
                "answer": "It depends on the salary. In Yukon in 2026, someone earning $40,000 keeps about 83.1% of gross pay, while someone earning $150,000 keeps about 71.9%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `

## Take-home pay in Yukon at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Yukon for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$33,255** | $2,771 | 83.1% |
| $60,000 | **$47,885** | $3,990 | 79.8% |
| $80,000 | **$61,039** | $5,087 | 76.3% |
| $100,000 | **$74,998** | $6,250 | 75.0% |
| $150,000 | **$107,893** | $8,991 | 71.9% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 83.1%; at $150,000 you keep 71.9%.

## Wage data for Yukon

Statistics Canada does not publish median wages by industry for the territories in Table 14-10-0064-01, so this guide does not estimate them. The take-home figures below come from the 2026 tax rules, which do apply.

## How Yukon compares with the rest of Canada

On an $80,000 salary, Yukon ranks **#4 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon ← | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between Yukon and Nunavut, the highest, is $1,260 a year on the same $80,000 salary — about $105 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Yukon

Most Yukon employees are in Whitehorse. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Yukon and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-northwest-territories',
    slug: 'northwest-territories-take-home-pay-guide-2026',
    title: "Northwest Territories Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Northwest Territories workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "What salaries in Northwest Territories leave after federal and territorial tax, CPP and EI in 2026, and how the territory compares with the rest of Canada.",
    metaTitle: "Northwest Territories Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "See take-home pay at every salary level in Northwest Territories for 2026, and how it ranks (#2 of 13) against every other province and territory.",
    keywords: ["Northwest Territories salary","Northwest Territories take home pay","Northwest Territories average salary 2026","Northwest Territories paycheck calculator","Northwest Territories income tax 2026","wages in Northwest Territories"],
    category: 'province',
    tags: ["Northwest Territories","take-home pay","wages","2026"],
    province: 'Northwest Territories',
    publishedAt: '2026-08-08',
    readTime: 6,
    imageUrl: '/blog/northwest-territories-take-home-pay-guide-2026.png',
    directAnswer: "On an $80,000 salary, Northwest Territories ranks #2 of 13 provinces and territories for take-home pay in 2026, keeping $61,166 after federal tax, territorial tax, CPP and EI.",
    faq: [
          {
                "question": "What is the average salary in Northwest Territories?",
                "answer": "Statistics Canada does not publish a median wage for Northwest Territories in its industry wage table, so this guide does not estimate one."
          },
          {
                "question": "What is the take-home pay on $80,000 in Northwest Territories?",
                "answer": "About $61,166 a year, or $5,097 a month, after federal tax, Northwest Territories provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Northwest Territories have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Northwest Territories ranks #2 of 13 provinces and territories for take-home pay in 2026, keeping $61,166. That is $1,133 a year less than Nunavut, the highest."
          },
          {
                "question": "Which industry pays best in Northwest Territories?",
                "answer": "Statistics Canada does not publish industry wage medians for Northwest Territories."
          },
          {
                "question": "How much of my pay do I keep in Northwest Territories?",
                "answer": "It depends on the salary. In Northwest Territories in 2026, someone earning $40,000 keeps about 83.4% of gross pay, while someone earning $150,000 keeps about 71.6%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `

## Take-home pay in Northwest Territories at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Northwest Territories for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$33,365** | $2,780 | 83.4% |
| $60,000 | **$47,938** | $3,995 | 79.9% |
| $80,000 | **$61,166** | $5,097 | 76.5% |
| $100,000 | **$75,204** | $6,267 | 75.2% |
| $150,000 | **$107,361** | $8,947 | 71.6% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 83.4%; at $150,000 you keep 71.6%.

## Wage data for Northwest Territories

Statistics Canada does not publish median wages by industry for the territories in Table 14-10-0064-01, so this guide does not estimate them. The take-home figures below come from the 2026 tax rules, which do apply.

## How Northwest Territories compares with the rest of Canada

On an $80,000 salary, Northwest Territories ranks **#2 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut | $62,299 |
| 2 | Northwest Territories ← | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

The difference between Northwest Territories and Nunavut, the highest, is $1,133 a year on the same $80,000 salary — about $94 a month.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Northwest Territories

Most Northwest Territories employees are in Yellowknife. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Northwest Territories and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
  {
    id: 'province-2026-nunavut',
    slug: 'nunavut-take-home-pay-guide-2026',
    title: "Nunavut Take-Home Pay Guide 2026: Real Wages, Real Deductions",
    subtitle: "What Nunavut workers actually earn by industry — and what lands in the bank after tax",
    excerpt: "What salaries in Nunavut leave after federal and territorial tax, CPP and EI in 2026, and how the territory compares with the rest of Canada.",
    metaTitle: "Nunavut Take-Home Pay Guide 2026 | Wages by Industry",
    metaDescription: "See take-home pay at every salary level in Nunavut for 2026, and how it ranks (#1 of 13) against every other province and territory.",
    keywords: ["Nunavut salary","Nunavut take home pay","Nunavut average salary 2026","Nunavut paycheck calculator","Nunavut income tax 2026","wages in Nunavut"],
    category: 'province',
    tags: ["Nunavut","take-home pay","wages","2026"],
    province: 'Nunavut',
    publishedAt: '2026-08-08',
    readTime: 6,
    imageUrl: '/blog/nunavut-take-home-pay-guide-2026.png',
    directAnswer: "On an $80,000 salary, Nunavut ranks #1 of 13 provinces and territories for take-home pay in 2026, keeping $62,299 after federal tax, territorial tax, CPP and EI.",
    faq: [
          {
                "question": "What is the average salary in Nunavut?",
                "answer": "Statistics Canada does not publish a median wage for Nunavut in its industry wage table, so this guide does not estimate one."
          },
          {
                "question": "What is the take-home pay on $80,000 in Nunavut?",
                "answer": "About $62,299 a year, or $5,192 a month, after federal tax, Nunavut provincial tax, CPP/CPP2 and EI for the 2026 tax year, for a single employee with no additional credits."
          },
          {
                "question": "Does Nunavut have high taxes compared with other provinces?",
                "answer": "On an $80,000 salary, Nunavut keeps the most take-home pay in the country in 2026 — $62,299 a year."
          },
          {
                "question": "Which industry pays best in Nunavut?",
                "answer": "Statistics Canada does not publish industry wage medians for Nunavut."
          },
          {
                "question": "How much of my pay do I keep in Nunavut?",
                "answer": "It depends on the salary. In Nunavut in 2026, someone earning $40,000 keeps about 84.5% of gross pay, while someone earning $150,000 keeps about 73.6%. The rest goes to federal tax, provincial tax, CPP/CPP2 and EI."
          }
    ],
    content: `

## Take-home pay in Nunavut at every salary level

Nobody is paid an "average". Here is what specific salaries actually leave in Nunavut for the 2026 tax year — federal tax, provincial tax, CPP/CPP2 and EI, for a single employee with no extra credits.

| Gross salary | Take-home (year) | Per month | Kept |
| --- | --- | --- | --- |
| $40,000 | **$33,784** | $2,815 | 84.5% |
| $60,000 | **$48,773** | $4,064 | 81.3% |
| $80,000 | **$62,299** | $5,192 | 77.9% |
| $100,000 | **$76,654** | $6,388 | 76.7% |
| $150,000 | **$110,408** | $9,201 | 73.6% |

Notice how the share you keep falls as the salary rises: that is Canada's progressive tax system working as designed. At $40,000 you keep 84.5%; at $150,000 you keep 73.6%.

## Wage data for Nunavut

Statistics Canada does not publish median wages by industry for the territories in Table 14-10-0064-01, so this guide does not estimate them. The take-home figures below come from the 2026 tax rules, which do apply.

## How Nunavut compares with the rest of Canada

On an $80,000 salary, Nunavut ranks **#1 of 13** provinces and territories for take-home pay in 2026.

| Rank | Province | Take-home on $80,000 |
| --- | --- | --- |
| 1 | Nunavut ← | $62,299 |
| 2 | Northwest Territories | $61,166 |
| 3 | British Columbia | $61,157 |
| 4 | Yukon | $61,039 |
| 5 | Alberta | $60,698 |
| 6 | Ontario | $60,303 |

Nunavut is the highest in the country on that salary. The next province keeps $61,166, a difference of $1,133 a year.

Take-home pay is only one side of a move, of course: rent, groceries and childcare vary as much as tax does. But it is the side most people guess at, and it is the side that can be calculated exactly.

## Where people work in Nunavut

Most Nunavut employees are in Iqaluit. Wherever you are in the province, the provincial tax rules are the same — there is no city income tax anywhere in Canada, so your postal code changes your rent, not your deductions.

## Run your own numbers

Every figure above is a median or a computed example. Your own pay depends on your exact salary or hourly rate, overtime, shift premiums, RRSP contributions and benefits. The [take-home pay calculator](/) handles all of it for Nunavut and every other province, for the 2026 tax year, with no signup.

*Wage figures: Statistics Canada, Table 14-10-0064-01, median hourly wage of full-time employees, 2025, annualised at 2,080 hours. Take-home figures: CanPay Insights 2026 tax engine (federal and provincial income tax, CPP/CPP2, EI) for a single employee with no additional credits.*`,
  },
];
