/**
 * The one place a blog-cover SVG gets its brand mark.
 *
 * WHY THIS FILE EXISTS: the mark was hand-drawn in SVG paths three separate
 * times and shipped wrong each time. The weekly article routine was even told
 * "copy the <!-- brand --> group verbatim from an existing cover" — which
 * faithfully copied a forgery, because every existing cover carried one.
 *
 * The real logo is public/logo.png and nothing else. Covers must EMBED it as
 * base64: an SVG loaded through <img> (which is how covers are used) cannot
 * fetch external references, so href="/logo.png" would silently render nothing.
 */
import { readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const SRC = 'public/logo.png';

/** 96px is plenty for a 40px mark on a 1200x630 cover and costs ~4.6 KB. */
function logoBase64(size = 96) {
  const out = join(tmpdir(), `canpay-logo-${size}.png`);
  if (!existsSync(out)) execFileSync('sips', ['-Z', String(size), SRC, '--out', out], { stdio: 'ignore' });
  return readFileSync(out).toString('base64');
}

/** The <!-- brand --> group: real logo + wordmark. Drop this into any cover. */
export function brandGroup({ x = 64, y = 70, size = 40 } = {}) {
  const b64 = logoBase64();
  return `  <!-- brand: generated by scripts/coverLogo.mjs — do NOT hand-edit or redraw -->
  <g transform="translate(${x}, ${y})">
    <clipPath id="logoClip"><rect width="${size}" height="${size}" rx="8"/></clipPath>
    <image width="${size}" height="${size}" clip-path="url(#logoClip)" xlink:href="data:image/png;base64,${b64}" href="data:image/png;base64,${b64}"/>
    <text x="${size + 16}" y="28" font-size="26" font-weight="bold" fill="#0f172a">CanPay <tspan fill="#dc2626" font-weight="normal">Insights</tspan></text>
  </g>`;
}

/** Opening tag with the xlink namespace the embedded <image> needs. */
export const SVG_OPEN =
  '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1200" height="630" viewBox="0 0 1200 630" font-family="Helvetica, Arial, sans-serif">';

if (process.argv[1] && process.argv[1].endsWith('coverLogo.mjs')) {
  process.stdout.write(brandGroup() + '\n');
}
